/*
 * Orkes Conductor API Server
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.orkes.conductor.client.http.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Map;
/**
 * SkipTaskRequest
 */


public class SkipTaskRequest {
  @SerializedName("taskInput")
  private Map<String, Object> taskInput = null;

  @SerializedName("taskOutput")
  private Map<String, Object> taskOutput = null;

  public SkipTaskRequest taskInput(Map<String, Object> taskInput) {
    this.taskInput = taskInput;
    return this;
  }

  public SkipTaskRequest putTaskInputItem(String key, Object taskInputItem) {
    if (this.taskInput == null) {
      this.taskInput = new HashMap<String, Object>();
    }
    this.taskInput.put(key, taskInputItem);
    return this;
  }

   /**
   * Get taskInput
   * @return taskInput
  **/
  @Schema(description = "")
  public Map<String, Object> getTaskInput() {
    return taskInput;
  }

  public void setTaskInput(Map<String, Object> taskInput) {
    this.taskInput = taskInput;
  }

  public SkipTaskRequest taskOutput(Map<String, Object> taskOutput) {
    this.taskOutput = taskOutput;
    return this;
  }

  public SkipTaskRequest putTaskOutputItem(String key, Object taskOutputItem) {
    if (this.taskOutput == null) {
      this.taskOutput = new HashMap<String, Object>();
    }
    this.taskOutput.put(key, taskOutputItem);
    return this;
  }

   /**
   * Get taskOutput
   * @return taskOutput
  **/
  @Schema(description = "")
  public Map<String, Object> getTaskOutput() {
    return taskOutput;
  }

  public void setTaskOutput(Map<String, Object> taskOutput) {
    this.taskOutput = taskOutput;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkipTaskRequest skipTaskRequest = (SkipTaskRequest) o;
    return Objects.equals(this.taskInput, skipTaskRequest.taskInput) &&
        Objects.equals(this.taskOutput, skipTaskRequest.taskOutput);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskInput, taskOutput);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkipTaskRequest {\n");
    
    sb.append("    taskInput: ").append(toIndentedString(taskInput)).append("\n");
    sb.append("    taskOutput: ").append(toIndentedString(taskOutput)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
