/*
 * Orkes Conductor API Server
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.orkes.conductor.client.http.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Map;
/**
 * TaskDetails
 */


public class TaskDetails {
  @SerializedName("output")
  private Map<String, Object> output = null;

  @SerializedName("taskId")
  private String taskId = null;

  @SerializedName("taskRefName")
  private String taskRefName = null;

  @SerializedName("workflowId")
  private String workflowId = null;

  public TaskDetails output(Map<String, Object> output) {
    this.output = output;
    return this;
  }

  public TaskDetails putOutputItem(String key, Object outputItem) {
    if (this.output == null) {
      this.output = new HashMap<String, Object>();
    }
    this.output.put(key, outputItem);
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @Schema(description = "")
  public Map<String, Object> getOutput() {
    return output;
  }

  public void setOutput(Map<String, Object> output) {
    this.output = output;
  }

  public TaskDetails taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @Schema(description = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public TaskDetails taskRefName(String taskRefName) {
    this.taskRefName = taskRefName;
    return this;
  }

   /**
   * Get taskRefName
   * @return taskRefName
  **/
  @Schema(description = "")
  public String getTaskRefName() {
    return taskRefName;
  }

  public void setTaskRefName(String taskRefName) {
    this.taskRefName = taskRefName;
  }

  public TaskDetails workflowId(String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @Schema(description = "")
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(String workflowId) {
    this.workflowId = workflowId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskDetails taskDetails = (TaskDetails) o;
    return Objects.equals(this.output, taskDetails.output) &&
        Objects.equals(this.taskId, taskDetails.taskId) &&
        Objects.equals(this.taskRefName, taskDetails.taskRefName) &&
        Objects.equals(this.workflowId, taskDetails.workflowId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(output, taskId, taskRefName, workflowId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskDetails {\n");
    
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskRefName: ").append(toIndentedString(taskRefName)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
