package io.orkes.conductor.client.http;

public class Mappers {
    public static final JSONMapper GSON_AUTOGENERATED = new JSON();
    // ObjectMapper-based will go here as well, we can create whatever specific modes we need here
}
